### ISSUE TITLE
tsconfig incompatible with Jest 18

### ISSUE THREAD

**Issue by KingHenne** [clebert/ts-config#58]
Jest (at least with version 18) can not handle the comments in the `tsconfig.json` file. Could you maybe remove them in a prepublish hook?

**Comment by clebert** [comment]
This will be fixed with https://github.com/clebert/ts-config/pull/59

**Comment by clebert** [comment]
It should be fixed with ts-config@9.2.0

**Comment by KingHenne** [comment]
Thanks! 👌🏻
