### ISSUE TITLE
Disable match-default-export-name tslint rule

### ISSUE THREAD

**Issue by fahrradflucht** [clebert/ts-config#89]
I always disable the tslint rule `match-default-export-name` when using `ts-config` because it requires the user to write a lot of unreadable import names for libraries. For example the `express` default export is named `e` and the default export of `isomorphic-fetch` is named `_fetch`.

Do you have a good reason for enabling it or would you maybe be fine with disabling it?

**Comment by clebert** [comment]
I think it leads to well-structured code when you name exports like the file containing them. But I don't recommend using default exports anyway. Therefore I disable the rule in the next version.
