### ISSUE TITLE
Consider opening up the TypeScript peerDependency range

### ISSUE THREAD

**Issue by fahrradflucht** [clebert/ts-config#90]
Is there a reasoning locking down the TypeScript peer dependency to the minor? I thought the whole ts versioning scheme is about the config so there should no config breaking updates between the minors. Just new features.

Opening it up would allow users to update before ts-config gets updated. For example at the moment TS 2.8 is out but updating hits my ocdish mind with peer dependency warnings.

**Comment by clebert** [comment]
Yeah, you're right. In the next version I will declare the dependencies semver-compatible.
