### ISSUE TITLE
feat: add init bin script for config generation

### ISSUE THREAD

**Issue by fahrradflucht** [clebert/ts-config#93]
What do you think of the idea to have a `ts-config init` script that creates the `tslint.json` and `tsconfig.json` mentioned in the README? I find myself constantly going in here and copying the 2 files contents when I create a new package.

**Comment by clebert** [comment]
Yeah, that's a good idea. I will implement it. I would suggest that you switch to this project: XXX. This is my follow-up project to this one. The automatically generated README makes rule overwriting much more transparent. Furthermore, this package is always backwards compatible from TSLint 5.10.0 by an adaptive creation .
